epoch: 100
grad_clip: -1
log_frequency: 250
first_layer: conv1

model: 
  name: ResNet18
  num_classes: 10

dataset:
  name: DatasetGenerator
  train_bs: 128
  eval_bs: 128

criterion:
  name: CrossEntropyLoss

optimizer:
  name: SGD
  lr: 0.01
  weight_decay: 5.e-4
  momentum: 0.9

scheduler:
  name: ExponentialLR
  gamma: 0.9
