epoch: 100
grad_clip: -1
log_frequency: 250
first_layer: conv1

model: 
  name: resnet18
  weights: ResNet18_Weights.DEFAULT

dataset:
  name: DatasetGenerator
  train_bs: 128
  eval_bs: 128

criterion:
  name: CrossEntropyLoss

optimizer:
  name: SGD
  lr: 0.1
  weight_decay: 5.e-4
  momentum: 0.9

scheduler:
  name: MultiStepLR
  milestones: [45, 75, 90]
  gamma: 0.1
