epoch: 200
grad_clip: -1
log_frequency: 1
target_layer: layer4.1.conv2

model: 
  name: ResNet18
  num_classes: 10

dataset:
  name: DatasetGenerator
  train_bs: 256
  eval_bs: 256
  train_d_type: "STL10"
  test_d_type: "STL10"
  train_tf_op: 'STL10'
  test_tf_op: 'STL10'
  n_workers: 8


criterion:
  name: CrossEntropyLoss

optimizer:
  name: Adam
  lr: 0.001
  weight_decay: 5.e-4

scheduler:
  name: ExponentialLR
  gamma: 0.9
