epoch: 80
grad_clip: -1
log_frequency: 250
target_layer: features.26

model: 
  name: VGG
  num_classes: 10
  vgg_name: VGG11

dataset:
  name: DatasetGenerator
  train_bs: 128
  eval_bs: 128

criterion:
  name: CrossEntropyLoss

optimizer:
  name: SGD
  lr: 0.001
  weight_decay: 5.e-4
  momentum: 0.9

scheduler:
  name: MultiStepLR
  milestones: [25, 40, 65]
  gamma: 0.1

