epoch: 100
grad_clip: -1
log_frequency: 250
target_layer: features.26

model: 
  name: VGG
  num_classes: 10
  vgg_name: VGG11

dataset:
  name: DatasetGenerator
  train_bs: 256
  eval_bs: 256
  n_workers: 4

criterion:
  name: CrossEntropyLoss

optimizer:
  name: SGD
  lr: 0.01
  weight_decay: 5.e-4
  momentum: 0.9

scheduler:
  name: ExponentialLR
  gamma: 0.9
