epoch: 200
grad_clip: -1
log_frequency: 10
target_layer: features.26

model: 
  name: VGG
  num_classes: 10
  vgg_name: VGG11

dataset:
  name: DatasetGenerator
  train_bs: 256
  eval_bs: 256
  train_d_type: "STL10"
  test_d_type: "STL10"
  train_tf_op: 'STL10'
  test_tf_op: 'STL10'
  n_workers: 8


criterion:
  name: CrossEntropyLoss

optimizer:
  name: SGD
  lr: 0.001
  weight_decay: 5.e-4
  momentum: 0.9

scheduler:
  name: ExponentialLR
  gamma: 0.9
